main(){
  int a=10;
  int b=20;
  int c=0;
  c=a+b;
  print("c=a+b=$c");
  c+=a;
  print("c+=a=$c");
  c-=a;
  print("c-=a=$c");
  c*=a;
  print("c*=a=$c");
  a = 10;
  c = 15;
  c ~/= a ;
  print("c ~/= a = $c ");
  a = 10;
  c = 15;
  c %= a ;
  c <<= 2 ;
  print("c <<= 2 = $c ");
  c >>= 2 ;
  print("c >>= 2 = $c ");
  c >>= 2 ;
  print("c >>= 2 = $c ");
  print("c %= a = $c ");
  c &= a ;
  print("c &= a = $c " );
  c ^= a ;
  print("c ^= a = $c " );
  c |= a ;
  print("c |= a = $c ");
}